### PR TITLE
Edit README and Project.toml for Pkg-Registration

### PR DESCRIPTION
**Pull request by antimon2**

### CODE REVIEW

**Comment by antimon2** [comment]
@JuliaRegistrator register()

**Comment by antimon2** [comment]
@4kimov 
Please approve the addition of the JuliaTeam Registrator to the GitHub Apps for this repository for semi-automatic registration of Julia packages.
ref: https://github.com/JuliaRegistries/Registrator.jl

**Comment by 4kimov** [comment]
Hi @antimon2, done. Please let me know if you're still having trouble.

**Comment by antimon2** [comment]
@JuliaRegistrator register

**Comment by antimon2** [comment]
@4kimov OK, Thanks!

**Comment by antimon2** [comment]
@4kimov 
Package auto-registration was blocked due to the following reasons:

+ Repository name is not `Sqids.jl` but `sqids-julia`
+ The name is deemed too simplistic and potentially confusing with existing packages like `Gaius`, `Folds`

(Reference: https://github.com/JuliaRegistries/General/pull/87546#issuecomment-1636754557 , https://julialang.github.io/Pkg.jl/dev/creating-packages/#Package-naming-guidelines-1)

For the first issue, can you rename the repository?
Regarding the second issue, I'll inquire if we can proceed registration with name `Sqids` since it's the same as a similarly functional package in another language, and while simple, is distinctly different from `Gaius` and `Folds` to the naked eye.

**Comment by 4kimov** [comment]
@antimon2 Thanks for the updates. We have over 40 repositories with the same naming convention. The convention is also integrated into the website. How can we unblock this without renaming?

**Comment by antimon2** [comment]
@4kimov 
Alright, since the block pertains to automatic registration, I will reach out to the Julia Package Registry to inquire about manual registration.

**Pull request merged**
